Repository ocsf/splunk, pull requests merged in 2024-09, with the labels that each got.

#29 SESA-1320: Fix broken string subtypes in 1.0.0-rc.2
  README.md
  dictionary.json
  extension.json
Labels: bug, non-breaking

#30 Add category_id to dictionary
  dictionary.json
  extension.json
Labels: bug, enhancement

#31 Add file_result to Network File Activity class
  events/network/file_activity.json
  extension.json
Labels: enhancement, non-breaking

#32 Add-forward_addr
  dictionary.json
  extension.json
  objects/account.json
  objects/user_ex.json
Labels: enhancement, non-breaking
