Repository ocsf/splunk, pull requests merged in 2024-07, with the labels that each got.

#23 Adding missing attributes, adding analytic object
  dictionary.json
  extension.json
  objects/analytic.json
Labels: bug, non-breaking

#25 SESA-1296 Add autonomous_system object, update ext version
  dictionary.json
  extension.json
  objects/autonomous_system.json
  objects/network_endpoint_ex.json
Labels: enhancement, non-breaking

#26 Downgrade dst_endpoint to recommended to match 1.x
  events/audit/authentication.json
  extension.json
Labels: non-breaking

#27 Add http_request, roll minor version
  events/audit/entity.json
  extension.json
Labels: non-breaking
